name: actions file for nodejs code
on: [push]
jobs:
  initializing-and-testing-code:
    runs-on: ubuntu-latest
    steps:
      - name: checking-out-repo
        uses: actions/checkout@v2
      
      - name: setting up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          
      - run: npm install
      - run: npm test
  
  pushing-the-image-to-docker-hub:
    needs: initializing-and-testing-code
    runs-on: ubuntu-latest
    steps:
      - name: checking-out-repo
        uses: actions/checkout@v2
      
      - name: logging-into-dockerhub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: build-and-push-docker-image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: vaibhavkaushikalpha09/expressnodeapp
          
  copying-compose-on-ec2:
    needs: [initializing-and-testing-code, pushing-the-image-to-docker-hub]
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repo
        uses: actions/checkout@master
      - name: coying docker-compose to the ec2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "docker-compose.yml"
          target: "code"
          
  bringing-up-docker-compose:
    needs: copying-compose-on-ec2
    runs-on: ubuntu-latest
    steps:
      - name: running the shell command for docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            docker rm nodeapp
            cd code/ && docker-compose up -d
